# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Hi! I'm Billy Nicart

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: The Coder

description: Stylish Jekyll Theme
author:
  name: Billy Nicart Jr
  email: billy.nicart@gmail.com
  github: bnicart
  twitter: itsmebilly1201
  pinterest:
  linkedin:
  bio: Software Developer who likes to play around with codes.
  email_md5:

rss_path:
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
